/* ----------------------------------------------------------------------
    OpenEdge:
    Impurity Transport in Modeling of SOL and Edge Physics:
    This code built on top of SPARTA, a parallel DSMC code.
    Abdourahmane Diaw,  diawa@ornl.gov (2023)
    Oak Ridge National Laboratory
https://github.com/ORNL-Fusion/OpenEdge
------------------------------------------------------------------------- */

#ifdef FIX_CLASS

FixStyle(efield/particle,FixEfieldParticle)

#else

#ifndef SPARTA_FIX_EFIELD_PARTICLE_H
#define SPARTA_FIX_EFIELD_PARTICLE_H

#include "stdio.h"
#include "fix.h"

namespace SPARTA_NS {

class FixEfieldParticle : public Fix {
 public:
  FixEfieldParticle(class SPARTA *, int, char **);
  ~FixEfieldParticle();
  int setmask();
  void init();
  void compute_field();

 private:
  char *axstr,*aystr,*azstr;
  int axvar,ayvar,azvar;
  int maxparticle;
};

}

#endif
#endif

/* ERROR/WARNING messages:

E: Illegal ... command

Self-explanatory.  Check the input script syntax and compare to the
documentation for the command.  You can use -echo screen as a
command-line option when running SPARTA to see the offending line.

E: Cannot open fix print file %s

The output file generated by the fix print command cannot be opened

*/
