/* ----------------------------------------------------------------------
    OpenEdge:
    Impurity Transport in Modeling of SOL and Edge Physics:
    This code built on top of SPARTA, a parallel DSMC code.
    Abdourahmane Diaw,  diawa@ornl.gov (2023)
    Oak Ridge National Laboratory
https://github.com/ORNL-Fusion/OpenEdge
------------------------------------------------------------------------- */

#ifdef FIX_CLASS

FixStyle(bfield/grid,FixBfieldGrid)

#else

#ifndef SPARTA_FIX_BFIELD_GRID_H
#define SPARTA_FIX_BFIELD_GRID_H

#include "stdio.h"
#include "fix.h"

namespace SPARTA_NS {

class FixBfieldGrid : public Fix {
 public:
  FixBfieldGrid(class SPARTA *, int, char **);
  ~FixBfieldGrid();
  int setmask();
  void init();
  void compute_field();

 private:
  char *axstr,*aystr,*azstr;
  int axvar,ayvar,azvar;
  int maxgrid;

// --- New: allow sourcing from a compute column c_ID[idx] ---
  enum SrcKind { SRC_NONE, SRC_VAR, SRC_COMP };
  struct GridSrc {
    SrcKind kind = SRC_NONE;
    int     varid = -1;      // for SRC_VAR
    int     icompute = -1;   // for SRC_COMP   (index into modify->compute[])
    int     col = 0;         // 1-based column: c_ID[col]
    char   *cid = nullptr;   // owned string ID
  };
  GridSrc sx, sy, sz;

  // helpers
  void   parse_src_token(const char *tok, GridSrc &dst, const char *label);
  void   bind_compute(GridSrc &S, const char *label);
  void   fill_from_compute(const GridSrc &S, int icol);

};

}

#endif
#endif

/* ERROR/WARNING messages:

E: Illegal ... command

Self-explanatory.  Check the input script syntax and compare to the
documentation for the command.  You can use -echo screen as a
command-line option when running SPARTA to see the offending line.

E: Cannot open fix print file %s

The output file generated by the fix print command cannot be opened

*/