#!/usr/bin/env python3
"""Generate input/srate.deck — the time-dependent IPD emitter for in.st40.

in.st40 is the canonical deck (edit it directly); it pulls the generated
`variable srate` / `variable nweight` lines via `include input/srate.deck`.
Re-run this script only when the source-rate data or the knobs below change.

S_PLOT is Erin's measured Li source rate for shot 14457, digitized from the
plots in ipd_source_demo.html — REPLACE with her CSV/MDS export when it
arrives. Plot time axis = arrival-at-plasma time (light-gate signal already
shifted by the 360 ms transit). Total 8.81 mg = 7.645e20 atoms.

Timing: grains fall gate -> dome port (~0.12 s) -> plasma (~0.24 s more).
Sim clock: t_sim = 0 at first dome passage = shot t = -200 ms, so the dome
emitter follows S_plot(t_sim + 40 ms) and arrivals land on the shot clock:
    shot_t = t_sim - 0.2 s
"""
import math
from pathlib import Path

S_PLOT = [(0, 0.05), (40, 0.10), (50, 0.55), (60, 0.95), (75, 1.45),
          (90, 2.00), (100, 2.40), (110, 2.75), (120, 3.10), (127, 3.28),
          (135, 3.00), (145, 2.70), (155, 2.45), (165, 2.25), (180, 1.95),
          (200, 1.55), (220, 1.30), (240, 1.10), (260, 0.95), (280, 0.82),
          (300, 0.73)]                      # (t_ms, S / 1e21 atoms/s)

DT, NEVERY = 2.0e-6, 200                    # must match in.st40
NSTEPS = 250000                             # formula covers this many steps
BLOCK_MS = 20                               # staircase resolution
NWEIGHT = 10                                # physical grains per macro-grain

R_GRAIN, RHO_LI = 5.0e-5, 534.0             # must match input/droplet.species
AMU = 1.66053906660e-27
ATOMS_PER_GRAIN = (4/3 * math.pi * R_GRAIN**3 * RHO_LI) / (6.941 * AMU)


def S_at(t_ms):                             # linear interp, hold ends
    ts = [p[0] for p in S_PLOT]
    ss = [p[1] for p in S_PLOT]
    if t_ms <= ts[0]: return ss[0]
    if t_ms >= ts[-1]: return ss[-1]
    for i in range(len(ts) - 1):
        if ts[i] <= t_ms <= ts[i + 1]:
            f = (t_ms - ts[i]) / (ts[i + 1] - ts[i])
            return ss[i] + f * (ss[i + 1] - ss[i])


def main():
    terms, n_events = [], []
    for k in range(0, int(NSTEPS * DT * 1e3), BLOCK_MS):
        s0, s1 = int(k * 1e-3 / DT), int((k + BLOCK_MS) * 1e-3 / DT)
        S21 = S_at(k + BLOCK_MS / 2 + 40.0)     # +40 ms plot-time offset
        n = S21 * 1e21 * NEVERY * DT / (ATOMS_PER_GRAIN * NWEIGHT)
        n_events.append(n)
        terms.append(f"(step>={s0})*(step<{s1})*{n:.2f}")
    # single token: no spaces (variable equal takes exactly one formula arg)
    srate = "+".join(terms) + "+1e-6"

    out = Path(__file__).resolve().parent / "input" / "srate.deck"
    with open(out, "w") as f:
        f.write("# generated by make_srate.py — do not edit by hand\n")
        f.write(f"# shot 14457 S(t), {len(terms)} x {BLOCK_MS} ms blocks, "
                f"peak feed {max(n_events)*NWEIGHT*ATOMS_PER_GRAIN/(NEVERY*DT):.2e} atoms/s\n")
        f.write(f"variable    nweight equal {NWEIGHT}\n")
        f.write(f"variable    srate equal {srate}\n")
    print(f"wrote {out}: {len(terms)} blocks, n/event "
          f"{min(n_events):.1f}..{max(n_events):.1f} (nweight {NWEIGHT})")


if __name__ == "__main__":
    main()
