#!/usr/bin/env python3
"""Extract a psi_norm = const contour from plasma.h5 equilibrium as a SPARTA
surface file.

Reads /equilibrium/{r, z, psi, psib} from a plasma.h5, computes
psi_norm = (psi - psi_axis) / (psib - psi_axis) with psi_axis = min(psi),
which matches the convention in fix_reflect_psi.cpp:290-326.  Picks the
contour at --psi-norm (default 0.95), selects the single closed contour
encircling the magnetic axis, and writes it as SPARTA surface lines.

Output coordinate convention matches wall.surf for axi layout: each point
is written as (Z, R) so SPARTA's x=Z / y=R mapping lines up unchanged.

Usage:
  python3 tools/extract_psi_contour.py \\
      --plasma-h5 examples/test_diii_d_neutrals/input/plasma.h5 \\
      --out       examples/test_diii_d_neutrals/input/core.surf \\
      --psi-norm  0.95

The resulting surface can be loaded in the deck as e.g.

  read_surf       input/core.surf group core particle check
  surf_collide    coreColl vanish
  surf_modify     core collide coreColl

which replaces `fix reflect/psi` for the core-absorb boundary.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import h5py
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def read_equilibrium(path: Path):
    with h5py.File(path, "r") as f:
        r = f["equilibrium/r"][:]
        z = f["equilibrium/z"][:]
        psi = f["equilibrium/psi"][:]
        psib = float(f["equilibrium/psib"][()])
    # Authoritative HDF5 layout per compute_plasma_fields.cpp:2223-2240:
    # psi.shape = (km, jm) = (nZ, nR), so psi[iZ, iR] is the value at
    # (Z = z[iZ], R = r[iR]).  Do NOT transpose: when nR == nZ a generic
    # shape-based transpose guard cannot distinguish the two orders and
    # silently corrupts the output.  If a future plasma.h5 ships psi in
    # the other order, the caller has to fix the converter, not us.
    assert psi.shape == (len(z), len(r)), (
        f"psi.shape {psi.shape} != (nZ={len(z)}, nR={len(r)}); "
        f"plasma.h5 layout differs from compute_plasma_fields.cpp convention")
    return r, z, psi, psib


def psi_norm_grid(psi: np.ndarray, psib: float) -> tuple[np.ndarray, float, float]:
    """Compute psi_norm = (psi - psi_axis)/(psib - psi_axis).  Returns (psin, psi_axis)."""
    psi_axis = float(np.nanmin(psi))
    dpsi = psib - psi_axis
    if abs(dpsi) < 1e-30:
        raise RuntimeError("degenerate equilibrium: psib == min(psi)")
    psin = (psi - psi_axis) / dpsi
    return psin, psi_axis


def select_inner_contour(paths, r_axis_guess: float, z_axis_guess: float):
    """Pick the closed contour encircling (r_axis, z_axis)."""
    best_path = None
    best_dmin = np.inf
    for p in paths:
        if len(p) < 4:
            continue
        # only consider closed contours (first ~= last, within 1e-6)
        if not np.allclose(p[0], p[-1], atol=1e-6):
            continue
        # check if (r_axis, z_axis) is inside this polygon
        # use ray casting
        inside = _point_in_poly(r_axis_guess, z_axis_guess, p)
        if not inside:
            continue
        # prefer the one whose bounding box is smallest (innermost)
        dmin = (p[:, 0].max() - p[:, 0].min()) + (p[:, 1].max() - p[:, 1].min())
        if dmin < best_dmin:
            best_dmin = dmin
            best_path = p
    return best_path


def _point_in_poly(x: float, y: float, poly: np.ndarray) -> bool:
    """Ray-casting point-in-polygon. poly: (N,2) array, (x, y) rows."""
    n = len(poly)
    inside = False
    j = n - 1
    for i in range(n):
        xi, yi = poly[i]
        xj, yj = poly[j]
        if ((yi > y) != (yj > y)) and (x < (xj - xi) * (y - yi) / (yj - yi + 1e-30) + xi):
            inside = not inside
        j = i
    return inside


def write_surf_axi(out: Path, R_Z_pts: np.ndarray):
    """Write a SPARTA 2D surface file with (Z, R) point coordinates for axi
    layout (SPARTA x = Z, y = R).

    R_Z_pts: (N, 2) array where column 0 = R, column 1 = Z.
    """
    pts_ZR = np.column_stack([R_Z_pts[:, 1], R_Z_pts[:, 0]])   # (Z, R)
    n = len(pts_ZR)
    with out.open("w") as f:
        f.write("# SPARTA surface file (axi layout: cols are Z, R)\n")
        f.write("# Generated by tools/extract_psi_contour.py\n\n")
        f.write(f"{n} points\n")
        f.write(f"{n} lines\n\n")
        f.write("Points\n\n")
        for i, (zz, rr) in enumerate(pts_ZR, start=1):
            f.write(f"{i} {zz:.10e} {rr:.10e}\n")
        f.write("\nLines\n\n")
        # closed loop: N segments 1->2, 2->3, ..., N->1
        for i in range(1, n + 1):
            j = i + 1 if i < n else 1
            f.write(f"{i} {i} {j}\n")


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--plasma-h5", type=Path, required=True)
    p.add_argument("--out",       type=Path, required=True)
    p.add_argument("--psi-norm",  type=float, default=0.95,
                   help="Normalized psi level for the contour (default 0.95)")
    p.add_argument("--preview",   type=Path, default=None,
                   help="Optional PNG showing the contour on a psi_norm map")
    args = p.parse_args(argv)

    r, z, psi, psib = read_equilibrium(args.plasma_h5)
    psin, psi_axis = psi_norm_grid(psi, psib)
    print(f"psi_axis = {psi_axis:+.4e}  psib = {psib:+.4e}", file=sys.stderr)
    print(f"R range [{r.min():.3f}, {r.max():.3f}]  Z range [{z.min():.3f}, {z.max():.3f}]",
          file=sys.stderr)

    # Locate the magnetic axis (R, Z of psi_axis) as a point the target contour
    # should enclose.
    iZ_ax, iR_ax = np.unravel_index(np.argmin(psi), psi.shape)
    R_ax = float(r[iR_ax]); Z_ax = float(z[iZ_ax])
    print(f"magnetic axis ~ (R={R_ax:.3f}, Z={Z_ax:.3f})", file=sys.stderr)

    # Extract contour paths with matplotlib.  The returned QuadContourSet has
    # .allsegs[level_index] = list of (N, 2) arrays in (x, y) = (R, Z).
    fig, ax = plt.subplots()
    RR, ZZ = np.meshgrid(r, z)
    cs = ax.contour(RR, ZZ, psin, levels=[args.psi_norm])
    segs = cs.allsegs[0]
    plt.close(fig)
    print(f"contour produced {len(segs)} segments", file=sys.stderr)

    path = select_inner_contour(segs, R_ax, Z_ax)
    if path is None:
        sys.exit(f"Could not find a closed contour at psi_norm={args.psi_norm} "
                 f"enclosing the magnetic axis")
    # Drop the duplicate closing vertex -- SPARTA's Lines block already
    # wraps N -> 1.
    if np.allclose(path[0], path[-1], atol=1e-8):
        path = path[:-1]
    print(f"selected contour: {len(path)} unique vertices, "
          f"R in [{path[:,0].min():.3f}, {path[:,0].max():.3f}], "
          f"Z in [{path[:,1].min():.3f}, {path[:,1].max():.3f}]",
          file=sys.stderr)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    write_surf_axi(args.out, path)
    print(f"wrote {args.out}", file=sys.stderr)

    if args.preview:
        fig, ax = plt.subplots(figsize=(8, 10))
        im = ax.pcolormesh(RR, ZZ, psin, shading="auto", cmap="viridis",
                           vmin=0.0, vmax=1.2)
        # Draw every returned contour segment in its own color and label its
        # vertex count + closure so the user can see which one was picked and
        # whether others exist at the same psi_norm level.
        colors = ["red", "orange", "magenta", "cyan", "lime", "white"]
        for i, seg in enumerate(segs):
            color = colors[i % len(colors)]
            closed = (len(seg) > 1 and np.allclose(seg[0], seg[-1], atol=1e-6))
            is_chosen = (path is not None and len(seg) == len(path) + 1 and
                         np.allclose(seg[:-1], path, atol=1e-9))
            lw = 2.2 if is_chosen else 0.8
            tag = f"seg{i} n={len(seg)} {'closed' if closed else 'open'}" \
                  f"{' <- SELECTED' if is_chosen else ''}"
            ax.plot(seg[:, 0], seg[:, 1], color=color, linewidth=lw, label=tag)
        # Magnetic axis
        ax.plot(R_ax, Z_ax, marker="*", color="yellow", markersize=16,
                markeredgecolor="black", label=f"mag axis ({R_ax:.3f}, {Z_ax:.3f})")
        # Annotate 8 evenly-spaced vertices of the selected contour with (R, Z)
        if path is not None and len(path) >= 8:
            N_LBL = 8
            idx = np.linspace(0, len(path) - 1, N_LBL, dtype=int)
            for k in idx:
                R, Z = path[k]
                ax.plot(R, Z, "k.", ms=3)
                ax.annotate(f"({R:.2f},{Z:+.2f})",
                            xy=(R, Z),
                            xytext=(6, 4),
                            textcoords="offset points",
                            fontsize=7, color="black",
                            bbox=dict(boxstyle="round,pad=0.15",
                                      facecolor="white", edgecolor="black",
                                      alpha=0.85, linewidth=0.3))
        ax.set_aspect("equal")
        ax.set_xlabel("R [m]"); ax.set_ylabel("Z [m]")
        ax.set_title(f"psi_norm = {args.psi_norm} contour (all segments shown)")
        ax.legend(loc="upper right", fontsize=7, framealpha=0.85)
        fig.colorbar(im, ax=ax, label=r"$\psi_n$")
        args.preview.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(args.preview, dpi=140, bbox_inches="tight")
        print(f"wrote preview {args.preview}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
