#!/usr/bin/env python3
"""
Generate SPARTA species/mixture/reactions entries for a tracked impurity
species over a range of charge states, for use with OpenEdge PMI runs.

Two outputs:

  1. A SPARTA ``species`` + ``mixture`` snippet you can paste into your
     ``in.*`` file (covers the neutral through Zmax+ charge states of a
     given element).

  2. A ``surf_react pmi eckstein`` reactions file with the standard three
     channels (TRIM reflection, Eckstein sputtering, and a catch-all
     absorb) for every charge state in the range.

The element lookup table is the same one used by the runtime (EIRENE
SPUTER via ``src/OPENEDGE/eckstein_sputter_data.h``), so self-sputtering
entries like ``W_on_W`` must exist there for the generated file to load.

Examples:

  # Print species + mixture block for W up to W30+ (neutral + 30 charge states)
  python3 tools/gen_pmi_species.py species --element W --zmax 30

  # Write a reactions file for W self-sputter/reflect on a W target
  python3 tools/gen_pmi_species.py reactions --element W --zmax 30 \
      --target W --out examples/test_west_axi/input/reactions_pmi_west_eckstein.surf

  # Do both at once and patch an existing input file in-place
  python3 tools/gen_pmi_species.py patch --element W --zmax 30 \
      --input examples/test_west_axi/in.west \
      --species-file input/plasma.species \
      --mixture tungstenSource \
      --reactions-file examples/test_west_axi/input/reactions_pmi_west_eckstein.surf \
      --target W

Notes:
  - ``patch`` replaces the existing ``species <file> ...`` line and the
    matching ``mixture <name> W* frac <v>`` block in-place. The
    reactions file is rewritten unconditionally when --reactions-file
    is given.
  - The species file (e.g. ``input/plasma.species``) must already define
    every charge state you ask for. Current OpenEdge species files ship
    with W up through W73+ and O through O8+, so W--Zmax up to 30 is
    fine out of the box.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def charge_label(element: str, z: int) -> str:
    if z == 0:
        return element
    if z == 1:
        return f"{element}+"
    return f"{element}{z}+"


def species_names(element: str, zmax: int) -> list[str]:
    return [charge_label(element, z) for z in range(zmax + 1)]


def render_species_line(species_file: str, element: str, zmax: int) -> str:
    names = species_names(element, zmax)
    return f"species {species_file} " + " ".join(names)


def render_mixture_block(mixture: str, element: str, zmax: int) -> str:
    lines = []
    names = species_names(element, zmax)
    # neutral gets frac 1, every ion gets frac 0 (PMI emits neutrals;
    # the charge-state cascade fills the others via chem/adas).
    width = max(len(n) for n in names)
    for i, n in enumerate(names):
        frac = "1." if i == 0 else "0."
        lines.append(f"mixture             {mixture}  {n:<{width}} frac {frac}")
    return "\n".join(lines)


def render_reactions_file(element: str, zmax: int, target: str) -> str:
    """
    Emit a surf_react pmi eckstein reactions file with
        - reflection via the TRIM table
        - sputtering via the Eckstein analytic formula
        - catch-all absorb (probability 1)
    for every charge state Z=0..zmax. Entry name is "<element>_on_<target>".
    """
    entry = f"{element}_on_{target}"
    lines = [
        f"# PMI surface reactions for {element} on {target}, generated by",
        f"# tools/gen_pmi_species.py. Covers neutral through Z={zmax}.",
        f"# Load with:",
        f"#   surf_react ID pmi eckstein <this-file> trim_dir <trim>",
        "",
    ]
    for z in range(zmax + 1):
        name = charge_label(element, z)
        lines.extend([
            f"{name} --> {element}",
            f"R Trim {entry}",
            "",
            f"{name} --> {element}",
            f"S Eckstein {entry}",
            "",
            f"{name} --> NULL",
            f"A Simple 1.0",
            "",
        ])
    return "\n".join(lines) + "\n"


def cmd_species(args):
    print(render_species_line(args.species_file, args.element, args.zmax))
    print()
    print(render_mixture_block(args.mixture, args.element, args.zmax))


def cmd_reactions(args):
    text = render_reactions_file(args.element, args.zmax, args.target)
    if args.out:
        Path(args.out).write_text(text)
        print(f"wrote {args.out}")
    else:
        sys.stdout.write(text)


def cmd_patch(args):
    path = Path(args.input)
    text = path.read_text()
    element = args.element
    names = species_names(element, args.zmax)

    # Replace "species <species_file> <names>" line.
    sp_re = re.compile(
        r"^species\s+\S+\s+"
        + r"(?:" + re.escape(element) + r"[0-9]*\+?\s*)+",
        re.MULTILINE,
    )
    new_species = render_species_line(args.species_file, element, args.zmax) + "\n"
    if sp_re.search(text):
        text = sp_re.sub(new_species, text, count=1)
    else:
        print("WARN: could not find existing 'species ... <element>' line; not patched", file=sys.stderr)

    # Replace mixture block for the given mixture name (contiguous lines).
    mix_line_re = re.compile(
        r"^mixture\s+" + re.escape(args.mixture) + r"\s+" +
        re.escape(element) + r"[0-9]*\+?\s+frac\s+\S+\s*$",
        re.MULTILINE,
    )
    matches = list(mix_line_re.finditer(text))
    if matches:
        start = matches[0].start()
        end = matches[-1].end()
        new_block = render_mixture_block(args.mixture, element, args.zmax) + "\n"
        text = text[:start] + new_block + text[end:]
    else:
        print("WARN: no existing mixture frac lines found; not patched", file=sys.stderr)

    path.write_text(text)
    print(f"patched {path}")

    if args.reactions_file:
        out = Path(args.reactions_file)
        out.write_text(render_reactions_file(element, args.zmax, args.target))
        print(f"wrote  {out}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    def add_common(sp):
        sp.add_argument("--element", required=True, help="Element symbol, e.g. W")
        sp.add_argument("--zmax", type=int, required=True, help="Maximum charge state (inclusive)")

    sp_species = sub.add_parser("species", help="Print species + mixture block")
    add_common(sp_species)
    sp_species.add_argument("--species-file", default="input/plasma.species",
                            help="Species file path as referenced by the 'species' command")
    sp_species.add_argument("--mixture", default="impuritySource",
                            help="Mixture name to use in the 'mixture' block")
    sp_species.set_defaults(func=cmd_species)

    sp_reactions = sub.add_parser("reactions", help="Write reactions_pmi_*.surf file")
    add_common(sp_reactions)
    sp_reactions.add_argument("--target", required=True, help="Target element symbol, e.g. W")
    sp_reactions.add_argument("--out", default=None, help="Output file path (default: stdout)")
    sp_reactions.set_defaults(func=cmd_reactions)

    sp_patch = sub.add_parser("patch", help="Patch an in.* file and write the reactions file in one shot")
    add_common(sp_patch)
    sp_patch.add_argument("--input", required=True, help="Path to the in.* file to patch in place")
    sp_patch.add_argument("--species-file", default="input/plasma.species")
    sp_patch.add_argument("--mixture", required=True, help="Mixture name to rewrite")
    sp_patch.add_argument("--reactions-file", default=None, help="If given, write a reactions file here")
    sp_patch.add_argument("--target", default=None, help="Target element (required with --reactions-file)")
    sp_patch.set_defaults(func=cmd_patch)

    args = p.parse_args()
    if args.cmd == "patch" and args.reactions_file and not args.target:
        p.error("--target is required when --reactions-file is given")
    args.func(args)


if __name__ == "__main__":
    main()
