# Settings for libraries used by specific SPARTA packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   -DSPARTA_UNORDERED_MAP -I/opt/homebrew/opt/hdf5/include
PKG_PATH =  
PKG_LIB =   -L/opt/homebrew/opt/hdf5/lib -lhdf5_cpp -lhdf5
PKG_CPP_DEPENDS = 
PKG_LINK_DEPENDS = 

PKG_SYSINC =  
PKG_SYSLIB =  
PKG_SYSPATH = 
